//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsRents
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRent
    {
        public int Id { get; set; }
        public string DriverName { get; set; }
        public string Passport { get; set; }
        public string DriverLicense { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
